web:
    build: .
    volumes:
        - "./:/usr/src/testrunner"
        - "../../../:/usr/src/plugin"
        - "./wordpress/:/usr/src/wordpress"
        - "./wordpress-develop/:/usr/src/wordpress-develop"
    links:
        - mysqldb:mysqldb
mysqldb:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wp
    ports:
        - "3306:3306"
